language: go
go_import_path: github.com/ethereumproject/go-ethereum

go: 1.7
os:
- linux
- osx

env:
- GETH_CMD=./geth-$TRAVIS_OS_NAME

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:duggan/bats --yes; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq bats; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bats; fi

script:
- go test ./...
- go build -o $GETH_CMD ./cmd/geth
- bats cmd/geth
